default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: db/production.postgresql
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: db/test.sqlite3

#production:
#  <<: *default
#  database: space-market_production
#  username: space-market
#  password: <%= ENV['SPACE-MARKET_DATABASE_PASSWORD'] %>
